[PETSC #16961] Error during compilation vpscat.c:1750: error: cannot convert ~QPetscInt*~R to ~Qint*~R for argument ~Q3~R to ~Qint MPI_Type_create_indexed_block(int, int,    int*, MPI_Datatype, MPI_Datatype*)~R                                                                                                  vpscat.c:1771: error: cannot convert ~QPetscInt*~R to ~Qint*~R for argument ~Q3~R to ~Qint MPI_Type_create_indexed_block(int, int,    int*, MPI_Datatype, MPI_Datatype*)~R
  Missing use of PetscMPIInt in MPI-2 calling code.