bk-changeset-1.3552.1.11 barrysmith@barry-smiths-computer.local|ChangeSet|20050926124040|29040 ChangeSet   1.3552.1.11 05/09/26 07:40:40 barrysmith@barry-smiths-computer.local +2 -0   state.c, petscimpl.h:      [PETSC #13716] Error while linking application     undefined reference to `PetscObjectStateIncrease(_p_PetscObject*)'     function was not extern "c" but was used in user code via VecRestoreArray()     changed to macro to resolve this problem and increase speed
  src/sys/objects/state.c
    1.17 05/09/26 07:32:57 barrysmith@barry-smiths-computer.local +0 -38
     [PETSC #13716] Error while linking application  
    undefined reference to `PetscObjectStateIncrease(_p_PetscObject*)'
    
    function was not extern "c" but was used in user code via VecRestoreArray()
    changed to macro to resolve this problem and increase speed

  include/private/petscimpl.h
    1.55 05/09/26 07:32:07 barrysmith@barry-smiths-computer.local +33 -1
     [PETSC #13716] Error while linking application  
    undefined reference to `PetscObjectStateIncrease(_p_PetscObject*)'
    
    function was not extern "c" but was used in user code via VecRestoreArray()
    changed to macro to resolve this problem and increase speed