bk-changeset-1.3552.13.1 barrysmith@barrysmith-57.mcs.anl.gov|ChangeSet|20050929154315|02614 ChangeSet   1.3552.13.1 05/09/29 10:43:15 barrysmith@barrysmith-57.mcs.anl.gov +9 -0   changed system to sys so would not conflict with   system include variables in TOPS interface
  several minor nightly build fixes

  src/tops/server/c++/TOPS_UnstructuredSolver_Impl.hh
    1.4 05/09/29 10:43:11 barrysmith@barrysmith-57.mcs.anl.gov +1 -1
    changed system to sys so would not conflict with
    system include variables

  src/tops/server/c++/TOPS_StructuredSolver_Impl.hh
    1.5 05/09/29 10:43:11 barrysmith@barrysmith-57.mcs.anl.gov +1 -1
    changed system to sys so would not conflict with
    system include variables

  python/PETSc/packages/MPI.py
    1.229 05/09/29 10:32:00 barrysmith@barrysmith-57.mcs.anl.gov +6 -1
    if Fortran compiler is f90 then tell MPI configure that it should use
    an F90 compiler
    otherwise
    configure:5094: f95 -w  -g  -c  conftest.f >&5
    f95: 1501-218 file conftest.f contains an incorrect file suffix
    configure:5097: $? = 1
    configure:5112: error: Could not compile Fortran test program

  src/mat/impls/dense/mpi/mpidense.c
    1.68 05/09/29 10:07:39 barrysmith@barrysmith-57.mcs.anl.gov +2 -20
    removed dead code that produces
    "mpidense.c", line 26: warning: statement not reached
    "mpidense.c", line 46: warning: statement not reached

  src/mat/utils/freespace.h
    1.7 05/09/29 09:56:09 barrysmith@barrysmith-57.mcs.anl.gov +1 -1
    left over keyword typedef from before I added PETSc namespacing
    In file included from aijfact.c:7:
    /sandbox/petsc/petsc-dev-2/src/mat/utils/freespace.h:15: warning: useless keyword or type name in empty declaration

  src/vec/vec/interface/vector.c
    1.141 05/09/29 09:50:45 barrysmith@barrysmith-57.mcs.anl.gov +1 -1
    fixed error barry introduced while redoing norm caching
    vector.c: In function `PetscErrorCode VecScale(_p_Vec*, std::complex<double>)':
    vector.c:760: error: cannot convert `std::complex<double>' to `double' in 
       assignment

  src/mat/impls/csr/inode/inode.c
    1.52 05/09/29 09:40:24 barrysmith@barrysmith-57.mcs.anl.gov +41 -26
    silly ibm compiler complains about negative array indices
    "inode.c", line 975.19: 1506-1300 (W) The subscript -1 is less than zero. The subscript of an array should be greater than or equal to zero.

  src/mat/interface/matrix.c
    1.194 05/09/29 09:31:32 barrysmith@barrysmith-57.mcs.anl.gov +4 -4
    silly ibm compiler complains about perfectly legal array index of -1
    "matrix.c", line 960.74: 1506-1300 (W) The subscript -1 is less than zero. The subscript of an array should be greater than or equal to zero.
    "matrix.c", line 970.74: 1506-1300 (W) The subscript -1 is less than zero. The subscript of an array should be greater than or equal to zero.

  src/sys/memory/mal.c
    1.29 05/09/29 09:29:02 barrysmith@barrysmith-57.mcs.anl.gov +7 -7
    silly IBM compiler warns about perfectly legal indexing into array of -1
    "mal.c", line 55.11: 1506-1300 (W) The subscript -1 is less than zero. The subscript of an array should be greater than or equal to zero.
    "mal.c", line 76.23: 1506-1300 (W) The subscript -1 is less than zero. The subscript of an array should be greater than or equal to zero.